[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"
  PYTHON_RUNTIME = "python3.9"

# Redirect all requests to the function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[dev]
  command = "python main.py"
  port = 5000