[build]
  command = "pip install -r requirements.txt && pip install -r functions/requirements.txt"
  functions = "functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"
  PYTHON_RUNTIME = "python3.9"

# Temporarily redirect to index function for debugging
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "python main.py"
  port = 5000