[build]
  command = "echo 'Build completed'"
  functions = "functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.8"

# Redirect all requests to the JavaScript app function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "python main.py"
  port = 5000