[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  NODE_VERSION = "18"

# Test function redirect only
[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000