[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Test function redirect
[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

# Redirect all requests to the JavaScript app function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "npm run dev"
  port = 3000