[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"
  # Environment variables for Supabase (set these in Netlify dashboard)
  # SUPABASE_URL = "https://bmfduwzdfdbdneliwyvc.supabase.co"
  # SUPABASE_ANON_KEY = "your-supabase-anon-key"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000
  
# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"