[build]
  command = "echo 'Build completed'"
  functions = "functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"
  PYTHON_RUNTIME = "python3.9"

# Redirect all requests to the index function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "python main.py"
  port = 5000