[build]
  command = "echo 'Build complete'"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  NODE_VERSION = "18"

# Main app redirects
[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000