[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Main app redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000